module.exports = [
"of thunder and lightning heard.", 
"pavilion on deck, with a curtain before it; PERICLES", 
"within it, reclined on a couch. A barge lying", 
"beside the Tyrian vessel.", 
"near the altar, as high priestess; a number of", 
"Virgins on each side; CERIMON and other Inhabitants", 
"of Ephesus attending.", 
"reception of King, Princess, Lords,  & c.", 
"lists. A pavilion by the side of it for the", 
"lying asleep.", 
"DON", 
"attending.",
"ANTIPHOLUS", 
"OF SYRACUSE", 
"OF EPHESUS", 
"BISHOP", 
"COUNTESS", 
"RICHARD", 
"Yorkshire.",
"SONG.", 
"a trunk in one corner of it.",
"Varro's",
"SCENE I:",
"Two Sentinels on guard.",
"soft music playing; Gentleman, and others attending.",
"Ghost",
"Eastcheap. The Boar's-Head Tavern.",
"An ante-chamber adjoining Imogen's apartments.",
"DUMB SHOW.",
]
